// vue-web/src/pages/ProvidersPage.vue
// Providers: search, add connection, edit modal, enable/disable, priority
// up/down (server renumbers), per-connection test + test-all, delete.
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { api } from "@/lib/api";
import { toast } from "@/lib/state";
import Badge from "@/components/Badge.vue";
import Toggle from "@/components/Toggle.vue";

interface Connection {
  id: string;
  provider: string;
  name?: string;
  email?: string;
  authType?: string;
  priority?: number;
  isActive?: boolean;
  testStatus?: string;
  lastError?: string;
  [key: string]: unknown;
}

const PROVIDER_CATEGORIES: Record<string, string[]> = {
  "API Key Providers": [
    "openrouter", "openai", "deepseek", "groq", "mistral", "xai",
    "anthropic", "gemini", "together", "fireworks", "siliconflow", "cohere",
    "nebius", "cerebras", "chutes", "perplexity",
  ],
  "Free / Open Providers": ["ollama-local", "kilo", "free-tier"],
};

const PROVIDER_OPTIONS = [
  { value: "openrouter", label: "OpenRouter (Recommended)" },
  { value: "openai", label: "OpenAI" },
  { value: "deepseek", label: "DeepSeek" },
  { value: "groq", label: "Groq" },
  { value: "anthropic", label: "Anthropic Claude" },
  { value: "gemini", label: "Google Gemini" },
  { value: "mistral", label: "Mistral AI" },
  { value: "xai", label: "xAI (Grok)" },
  { value: "together", label: "Together AI" },
  { value: "fireworks", label: "Fireworks AI" },
  { value: "siliconflow", label: "SiliconFlow" },
  { value: "cohere", label: "Cohere" },
  { value: "tokenrouter", label: "TokenRouter" },
  { value: "ollama-local", label: "Ollama (Local)" },
];

const providers = ref<Connection[]>([]);
const loading = ref(true);
const search = ref("");
const showAddForm = ref(false);
const selectedProvider = ref("openrouter");
const apiKey = ref("");
const name = ref("");
const creating = ref(false);
const testingId = ref<string | null>(null);
const testAllRunning = ref(false);

const editing = ref<Connection | null>(null);
const editName = ref("");
const editEmail = ref("");
const editApiKey = ref("");
const savingEdit = ref(false);

async function load() {
  loading.value = true;
  try {
    const data = await api.get<{ connections: Connection[] }>("/api/providers");
    providers.value = data.connections ?? [];
  } catch {
    toast.error("Failed to fetch providers");
  } finally {
    loading.value = false;
  }
}
onMounted(load);

const filtered = computed(() => {
  const q = search.value.trim().toLowerCase();
  if (!q) return providers.value;
  return providers.value.filter(
    (p) => (p.name ?? "").toLowerCase().includes(q) || p.provider.toLowerCase().includes(q),
  );
});

const activeCount = computed(() => providers.value.filter((p) => p.isActive !== false && p.testStatus === "active").length);
const errorCount = computed(() => providers.value.filter((p) => p.testStatus === "error").length);

function iconSrc(p: Connection) {
  return `/providers/${p.provider}.png`;
}

async function createProvider() {
  if (!selectedProvider.value.trim() || !apiKey.value.trim() || !name.value.trim()) return;
  creating.value = true;
  try {
    await api.post("/api/providers", {
      provider: selectedProvider.value.trim(),
      apiKey: apiKey.value.trim(),
      name: name.value.trim(),
    });
    toast.success(`Added provider "${name.value.trim()}"`);
    apiKey.value = "";
    name.value = "";
    showAddForm.value = false;
    await load();
  } catch {
    toast.error("Failed to add provider");
  } finally {
    creating.value = false;
  }
}

function openEdit(p: Connection) {
  editing.value = p;
  editName.value = p.name ?? "";
  editEmail.value = typeof p.email === "string" ? p.email : "";
  editApiKey.value = "";
}

async function saveEdit() {
  if (!editing.value) return;
  savingEdit.value = true;
  const patch: Record<string, unknown> = { name: editName.value.trim() };
  if (editEmail.value.trim()) patch.email = editEmail.value.trim();
  if (editApiKey.value.trim()) patch.apiKey = editApiKey.value.trim();
  try {
    await api.put(`/api/providers/${editing.value.id}`, patch);
    toast.success("Connection updated");
    editing.value = null;
    await load();
  } catch {
    toast.error("Failed to update connection");
  } finally {
    savingEdit.value = false;
  }
}

async function toggleActive(p: Connection) {
  const next = !(p.isActive !== false);
  try {
    await api.put(`/api/providers/${p.id}`, { isActive: next });
    toast.success(`"${p.name ?? p.provider}" ${next ? "enabled" : "disabled"}`);
    await load();
  } catch {
    toast.error("Failed to update connection");
  }
}

async function move(p: Connection, dir: -1 | 1) {
  const siblings = providers.value
    .filter((x) => x.provider === p.provider)
    .sort((a, b) => (a.priority ?? 99) - (b.priority ?? 99));
  const idx = siblings.findIndex((x) => x.id === p.id);
  const swap = siblings[idx + dir];
  if (!swap) return;
  try {
    await api.put(`/api/providers/${p.id}`, { priority: swap.priority ?? 99 });
    await load();
  } catch {
    toast.error("Failed to reorder");
  }
}

async function testOne(p: Connection): Promise<boolean> {
  testingId.value = p.id;
  try {
    const r = await api.post<{ valid: boolean; error: string | null }>(`/api/providers/${p.id}/test`);
    return !!r.valid;
  } catch {
    return false;
  } finally {
    testingId.value = null;
  }
}

async function handleTest(p: Connection) {
  const ok = await testOne(p);
  await load();
  if (ok) toast.success(`"${p.name ?? p.provider}" connection is working!`);
  else toast.error(`"${p.name ?? p.provider}" failed`, "Test Connection");
}

async function testAll() {
  testAllRunning.value = true;
  let pass = 0;
  let fail = 0;
  for (const p of filtered.value) {
    if (await testOne(p)) pass += 1;
    else fail += 1;
  }
  testAllRunning.value = false;
  await load();
  toast.success(`Test all done: ${pass} pass, ${fail} fail`, "Batch Test");
}

async function remove(p: Connection) {
  if (!confirm(`Delete connection "${p.name ?? p.provider}"?`)) return;
  try {
    await api.del(`/api/providers/${p.id}`);
    toast.success("Connection deleted");
    await load();
  } catch {
    toast.error("Failed to delete connection");
  }
}
</script>

<template>
  <div class="fade-in flex flex-col gap-6" style="max-width: 1000px">
    <!-- Actions row -->
    <div style="display: flex; justify-content: flex-end; align-items: center; flex-wrap: wrap; gap: 0.5rem">
      <Badge variant="success" dot>{{ activeCount }} Active</Badge>
      <Badge v-if="errorCount > 0" variant="danger" dot>{{ errorCount }} Error</Badge>
      <button class="kid-btn kid-btn--accent" style="padding: 0.3rem 0.75rem" :disabled="testAllRunning || filtered.length === 0" @click="testAll">
        <span class="material-symbols-outlined" style="font-size: 16px">science</span>
        {{ testAllRunning ? "Testing all…" : "Test All" }}
      </button>
      <button class="kid-btn kid-btn--primary" style="padding: 0.3rem 0.75rem" @click="showAddForm = !showAddForm">
        {{ showAddForm ? "✕ Close Form" : "＋ Add Provider" }}
      </button>
    </div>

    <input v-model="search" class="kid-input" placeholder="Search connections…" style="max-width: 360px" />

    <!-- Add form -->
    <div v-if="showAddForm" class="kid-card" style="background-color: var(--color-brand-50); border-color: var(--color-brand-500)">
      <h2 style="font-size: 1.25rem; margin: 0 0 1rem">＋ Add New AI Provider Connection</h2>
      <form style="display: grid; gap: 0.75rem" @submit.prevent="createProvider">
        <div style="display: grid; gap: 0.75rem; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr))">
          <div>
            <label style="display: block; font-family: var(--font-body); margin-bottom: 0.2rem; font-weight: 700">Provider</label>
            <select v-model="selectedProvider" class="kid-input" :disabled="creating">
              <option v-for="o in PROVIDER_OPTIONS" :key="o.value" :value="o.value">{{ o.label }}</option>
            </select>
          </div>
          <div>
            <label style="display: block; font-family: var(--font-body); margin-bottom: 0.2rem; font-weight: 700">Connection Name</label>
            <input v-model="name" class="kid-input" placeholder="e.g. Primary OpenRouter" :disabled="creating" />
          </div>
          <div style="grid-column: 1 / -1">
            <label style="display: block; font-family: var(--font-body); margin-bottom: 0.2rem; font-weight: 700">API Key / Token</label>
            <input v-model="apiKey" type="password" class="kid-input" placeholder="sk-..." :disabled="creating" />
          </div>
        </div>
        <div style="display: flex; justify-content: flex-end; gap: 0.5rem">
          <button type="button" class="kid-btn" :disabled="creating" @click="showAddForm = false">Cancel</button>
          <button type="submit" class="kid-btn kid-btn--primary" :disabled="creating || !name.trim() || !apiKey.trim()">
            {{ creating ? "Adding…" : "Save Connection" }}
          </button>
        </div>
      </form>
    </div>

    <p v-if="loading" style="font-family: var(--font-body)">Loading providers…</p>

    <div v-if="!loading && filtered.length === 0" class="kid-card" style="text-align: center; padding: 3rem 1rem">
      <h2 style="margin: 0.5rem 0">{{ providers.length === 0 ? "No AI Providers Configured" : "No matches" }}</h2>
      <p style="font-family: var(--font-body); color: var(--color-text-muted)">
        {{ providers.length === 0 ? "Add an OpenRouter, OpenAI, or DeepSeek API key to start routing AI requests!" : "Try a different search term." }}
      </p>
      <button v-if="providers.length === 0" class="kid-btn kid-btn--primary" style="margin-top: 1rem" @click="showAddForm = true">
        ＋ Add Your First Provider
      </button>
    </div>

    <div v-for="(cat, catName) in PROVIDER_CATEGORIES" :key="catName" style="margin-bottom: 1.5rem">
      <template v-if="filtered.filter((p) => cat.includes(p.provider) || catName.includes('API Key')).length > 0">
        <h2 style="font-size: 1.15rem; margin: 0 0 0.75rem; color: var(--color-text-muted)">{{ catName }}</h2>
        <div style="display: grid; gap: 1rem; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr))">
          <div
            v-for="p in filtered.filter((p) => cat.includes(p.provider) || catName.includes('API Key'))"
            :key="p.id"
            class="kid-card"
            :style="p.isActive === false ? { opacity: 0.55 } : undefined"
          >
            <div style="display: flex; justify-content: space-between; align-items: flex-start; gap: 0.5rem">
              <div style="display: flex; gap: 0.75rem; align-items: center">
                <img :src="iconSrc(p)" alt="" style="width: 36px; height: 36px; object-fit: contain" @error="($event.target as HTMLImageElement).style.visibility = 'hidden'" />
                <div>
                  <strong style="font-size: 1.2rem; display: block">{{ p.name ?? p.provider }}</strong>
                  <span style="font-family: var(--font-body); color: var(--color-text-muted); font-size: 0.9rem">
                    {{ p.provider }} · priority {{ p.priority ?? 99 }}
                  </span>
                </div>
              </div>
              <Badge :variant="p.testStatus === 'active' ? 'success' : p.testStatus === 'error' ? 'danger' : 'neutral'" size="sm" dot>
                {{ p.testStatus ?? "unknown" }}
              </Badge>
            </div>

            <div
              v-if="p.lastError"
              style="font-family: var(--font-body); font-size: 0.85rem; color: var(--color-danger); margin-top: 0.5rem; background: var(--color-bg-alt); padding: 0.3rem 0.5rem; border: 1px solid var(--nb-border)"
            >
              {{ p.lastError }}
            </div>

            <div style="display: flex; align-items: center; justify-content: space-between; margin-top: 0.85rem; gap: 0.5rem; flex-wrap: wrap">
              <div style="display: flex; align-items: center; gap: 0.4rem">
                <button class="kid-btn" style="padding: 0.2rem 0.5rem; font-size: 0.8rem" title="Raise priority" @click="move(p, -1)">▲</button>
                <button class="kid-btn" style="padding: 0.2rem 0.5rem; font-size: 0.8rem" title="Lower priority" @click="move(p, 1)">▼</button>
                <Toggle :checked="p.isActive !== false" @change="() => toggleActive(p)" />
              </div>
              <div style="display: flex; gap: 0.4rem">
                <button class="kid-btn" style="padding: 0.25rem 0.5rem" @click="openEdit(p)">
                  <span class="material-symbols-outlined" style="font-size: 16px">edit</span>
                </button>
                <button class="kid-btn kid-btn--accent" style="padding: 0.25rem 0.5rem" :disabled="testingId === p.id" @click="handleTest(p)">
                  <span class="material-symbols-outlined" :class="{ 'animate-spin': testingId === p.id }" style="font-size: 16px">
                    {{ testingId === p.id ? "progress_activity" : "science" }}
                  </span>
                </button>
                <button class="kid-btn" style="padding: 0.25rem 0.5rem; background: var(--color-danger); color: #fff" @click="remove(p)">
                  <span class="material-symbols-outlined" style="font-size: 16px">delete</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </template>
    </div>

    <!-- Edit modal -->
    <div
      v-if="editing"
      style="position: fixed; inset: 0; background: rgba(0,0,0,0.5); z-index: 100; display: flex; align-items: center; justify-content: center; padding: 1rem"
      @click.self="editing = null"
    >
      <form class="kid-card kid-wobble" style="width: min(420px, 100%); background: var(--color-surface)" @submit.prevent="saveEdit">
        <h3 style="font-size: 1.3rem; margin: 0 0 0.75rem">Edit Connection</h3>
        <div style="display: grid; gap: 0.6rem">
          <div>
            <label style="font-family: var(--font-body); font-size: 0.9rem">Name</label>
            <input v-model="editName" class="kid-input" :disabled="savingEdit" />
          </div>
          <div>
            <label style="font-family: var(--font-body); font-size: 0.9rem">Email (optional)</label>
            <input v-model="editEmail" type="email" class="kid-input" :disabled="savingEdit" />
          </div>
          <div>
            <label style="font-family: var(--font-body); font-size: 0.9rem">New API Key (leave blank to keep)</label>
            <input v-model="editApiKey" type="password" class="kid-input" placeholder="sk-…" :disabled="savingEdit" />
          </div>
        </div>
        <div style="display: flex; gap: 0.5rem; justify-content: flex-end; margin-top: 1.25rem">
          <button type="button" class="kid-btn" :disabled="savingEdit" @click="editing = null">Cancel</button>
          <button type="submit" class="kid-btn kid-btn--primary" :disabled="savingEdit || !editName.trim()">
            {{ savingEdit ? "Saving…" : "Save Changes" }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

// react-web/src/pages/ProvidersPage.tsx
// Rich Providers Page — ports 9Router's providers layout onto the crayon UI:
// search filter, add connection, per-connection edit (name/email/apiKey),
// enable/disable, priority up/down (server renumbers), Test, Test All, delete.
import { useEffect, useMemo, useState } from "react";
import { useProviderStore, type ProviderConnection } from "@/store/providerStore";
import { useNotificationStore } from "@/store/notificationStore";
import { Button, Badge, Card, Toggle } from "@/components/ui";
import ProviderIcon from "@/components/ProviderIcon";

const PROVIDER_CATEGORIES: Record<string, string[]> = {
  "API Key Providers": [
    "openrouter", "openai", "deepseek", "groq", "mistral", "xai",
    "anthropic", "gemini", "together", "fireworks", "siliconflow", "cohere",
    "nebius", "cerebras", "chutes", "perplexity"
  ],
  "Free / Open Providers": [
    "ollama-local", "kilo", "free-tier"
  ],
};

export default function ProvidersPage() {
  const providers = useProviderStore((s) => s.providers);
  const loading = useProviderStore((s) => s.loading);
  const error = useProviderStore((s) => s.error);
  const fetchProviders = useProviderStore((s) => s.fetchProviders);
  const createProvider = useProviderStore((s) => s.createProvider);
  const putProvider = useProviderStore((s) => s.putProvider);
  const deleteProvider = useProviderStore((s) => s.deleteProvider);
  const testProvider = useProviderStore((s) => s.testProvider);
  const notify = useNotificationStore();

  const [showAddForm, setShowAddForm] = useState(false);
  const [selectedProvider, setSelectedProvider] = useState("openrouter");
  const [apiKey, setApiKey] = useState("");
  const [name, setName] = useState("");
  const [creating, setCreating] = useState(false);
  const [testingId, setTestingId] = useState<string | null>(null);
  const [testAllRunning, setTestAllRunning] = useState(false);
  const [search, setSearch] = useState("");

  // Edit modal state
  const [editing, setEditing] = useState<ProviderConnection | null>(null);
  const [editName, setEditName] = useState("");
  const [editEmail, setEditEmail] = useState("");
  const [editApiKey, setEditApiKey] = useState("");
  const [savingEdit, setSavingEdit] = useState(false);

  useEffect(() => {
    fetchProviders();
  }, [fetchProviders]);

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return providers;
    return providers.filter(
      (p) =>
        (p.name ?? "").toLowerCase().includes(q) ||
        p.provider.toLowerCase().includes(q)
    );
  }, [providers, search]);

  const activeCount = providers.filter((p) => p.isActive !== false && p.testStatus === "active").length;
  const errorCount = providers.filter((p) => p.testStatus === "error").length;

  function connId(p: ProviderConnection): string {
    return p.id ?? p._id;
  }

  function priorityOf(p: ProviderConnection): number {
    return typeof p.priority === "number" ? p.priority : 99;
  }

  async function handleCreate(e: React.FormEvent) {
    e.preventDefault();
    if (!selectedProvider.trim() || !apiKey.trim() || !name.trim()) return;
    setCreating(true);
    const created = await createProvider({
      provider: selectedProvider.trim(),
      apiKey: apiKey.trim(),
      name: name.trim(),
    });
    setCreating(false);
    if (created) {
      notify.success(`Added provider "${created.name}"`);
      setApiKey("");
      setName("");
      setShowAddForm(false);
    } else {
      notify.error("Failed to add provider");
    }
  }

  function openEdit(p: ProviderConnection) {
    setEditing(p);
    setEditName(p.name ?? "");
    setEditEmail(typeof p.email === "string" ? p.email : "");
    setEditApiKey("");
  }

  async function handleSaveEdit(e: React.FormEvent) {
    e.preventDefault();
    if (!editing) return;
    setSavingEdit(true);
    const patch: Record<string, unknown> = { name: editName.trim() };
    if (editEmail.trim()) patch.email = editEmail.trim();
    if (editApiKey.trim()) patch.apiKey = editApiKey.trim();
    const updated = await putProvider(connId(editing), patch);
    setSavingEdit(false);
    if (updated) {
      notify.success("Connection updated");
      setEditing(null);
    } else {
      notify.error("Failed to update connection");
    }
  }

  async function handleToggleActive(p: ProviderConnection) {
    const next = !(p.isActive !== false);
    const updated = await putProvider(connId(p), { isActive: next });
    if (updated) notify.success(`"${p.name ?? p.provider}" ${next ? "enabled" : "disabled"}`);
    else notify.error("Failed to update connection");
  }

  // Swap this connection's priority with its neighbour; the backend renumbers
  // the whole provider group on a priority change.
  async function handleMove(p: ProviderConnection, dir: -1 | 1) {
    const siblings = providers
      .filter((x) => x.provider === p.provider)
      .sort((a, b) => priorityOf(a) - priorityOf(b));
    const idx = siblings.findIndex((x) => connId(x) === connId(p));
    const swapIdx = idx + dir;
    if (swapIdx < 0 || swapIdx >= siblings.length) return;
    const updated = await putProvider(connId(p), { priority: priorityOf(siblings[swapIdx]) });
    if (updated) {
      await fetchProviders({ force: true });
    } else {
      notify.error("Failed to reorder");
    }
  }

  async function handleTest(id: string, providerName: string) {
    setTestingId(id);
    const result = await testProvider(id);
    setTestingId(null);
    if (!result) {
      notify.error("Test request failed");
      return;
    }
    if (result.valid) notify.success(`"${providerName}" connection is working!`);
    else notify.error(`"${providerName}" failed: ${result.error ?? "Invalid key or endpoint"}`, "Test Connection");
  }

  async function handleTestAll() {
    setTestAllRunning(true);
    let pass = 0;
    let fail = 0;
    for (const p of filtered) {
      const result = await testProvider(connId(p));
      if (result?.valid) pass += 1;
      else fail += 1;
    }
    setTestAllRunning(false);
    notify.success(`Test all done: ${pass} pass, ${fail} fail`, "Batch Test");
  }

  async function handleDelete(id: string, providerName: string) {
    if (!confirm(`Delete connection "${providerName}"?`)) return;
    const ok = await deleteProvider(id);
    if (ok) notify.success("Connection deleted");
    else notify.error("Failed to delete connection");
  }

  return (
    <div className="fade-in flex flex-col gap-6" style={{ maxWidth: 1000 }}>
      {/* Actions row — page title lives in the Header (Node parity) */}
      <div style={{ display: "flex", justifyContent: "flex-end", alignItems: "center", flexWrap: "wrap", gap: "0.5rem" }}>
        <Badge variant="success" dot>{activeCount} Active</Badge>
        {errorCount > 0 && <Badge variant="danger" dot>{errorCount} Error</Badge>}
        <Button variant="accent" size="sm" onClick={handleTestAll} disabled={testAllRunning || filtered.length === 0}>
          {testAllRunning ? (
            <><span className="material-symbols-outlined" style={{ fontSize: 16 }}>science</span> Testing all…</>
          ) : (
            <><span className="material-symbols-outlined" style={{ fontSize: 16 }}>science</span> Test All</>
          )}
        </Button>
        <Button variant="primary" size="sm" onClick={() => setShowAddForm(!showAddForm)}>
          {showAddForm ? "✕ Close Form" : "＋ Add Provider"}
        </Button>
      </div>

      {/* Search */}
      <input
        className="kid-input"
        placeholder="Search connections…"
        value={search}
        onChange={(e) => setSearch(e.target.value)}
        style={{ maxWidth: 360 }}
      />

      {/* Add Provider Card */}
      {showAddForm && (
        <Card tilt={false} style={{ backgroundColor: "var(--color-brand-50)", borderColor: "var(--color-brand-500)" }}>
          <h2 style={{ fontSize: "1.3rem", marginTop: 0, marginBottom: "1rem" }}>＋ Add New AI Provider Connection</h2>
          <form onSubmit={handleCreate} style={{ display: "grid", gap: "0.75rem" }}>
            <div style={{ display: "grid", gap: "0.75rem", gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))" }}>
              <div>
                <label style={{ display: "block", fontFamily: "var(--font-body)", marginBottom: "0.2rem", fontWeight: 700 }}>
                  Provider
                </label>
                <select
                  className="kid-input"
                  value={selectedProvider}
                  onChange={(e) => setSelectedProvider(e.target.value)}
                  disabled={creating}
                >
                  <option value="openrouter">OpenRouter (Recommended)</option>
                  <option value="openai">OpenAI</option>
                  <option value="deepseek">DeepSeek</option>
                  <option value="groq">Groq</option>
                  <option value="anthropic">Anthropic Claude</option>
                  <option value="gemini">Google Gemini</option>
                  <option value="mistral">Mistral AI</option>
                  <option value="xai">xAI (Grok)</option>
                  <option value="together">Together AI</option>
                  <option value="fireworks">Fireworks AI</option>
                  <option value="siliconflow">SiliconFlow</option>
                  <option value="cohere">Cohere</option>
                  <option value="tokenrouter">TokenRouter</option>
                  <option value="ollama-local">Ollama (Local)</option>
                </select>
              </div>

              <div>
                <label style={{ display: "block", fontFamily: "var(--font-body)", marginBottom: "0.2rem", fontWeight: 700 }}>
                  Connection Name
                </label>
                <input
                  className="kid-input"
                  placeholder="e.g. Primary OpenRouter"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  disabled={creating}
                />
              </div>

              <div style={{ gridColumn: "1 / -1" }}>
                <label style={{ display: "block", fontFamily: "var(--font-body)", marginBottom: "0.2rem", fontWeight: 700 }}>
                  API Key / Token
                </label>
                <input
                  className="kid-input"
                  type="password"
                  placeholder="sk-..."
                  value={apiKey}
                  onChange={(e) => setApiKey(e.target.value)}
                  disabled={creating}
                />
              </div>
            </div>

            <div style={{ display: "flex", justifyContent: "flex-end", gap: "0.5rem", marginTop: "0.5rem" }}>
              <Button variant="secondary" type="button" onClick={() => setShowAddForm(false)} disabled={creating}>
                Cancel
              </Button>
              <Button variant="primary" type="submit" disabled={creating || !name.trim() || !apiKey.trim()}>
                {creating ? "Adding…" : "Save Connection"}
              </Button>
            </div>
          </form>
        </Card>
      )}

      {loading && <p style={{ fontFamily: "var(--font-body)" }}>Loading providers…</p>}
      {error && <Card style={{ backgroundColor: "var(--color-danger)", color: "#fff" }}>{error}</Card>}

      {/* Connected Providers List */}
      {!loading && filtered.length === 0 && (
        <Card style={{ textAlign: "center", padding: "3rem 1rem" }}>
          <div style={{ fontSize: "3rem" }}>🤖</div>
          <h2 style={{ margin: "0.5rem 0" }}>{providers.length === 0 ? "No AI Providers Configured" : "No matches"}</h2>
          <p style={{ fontFamily: "var(--font-body)", color: "var(--color-text-muted)" }}>
            {providers.length === 0
              ? "Add an OpenRouter, OpenAI, or DeepSeek API key to start routing AI requests!"
              : "Try a different search term."}
          </p>
          {providers.length === 0 && (
            <Button variant="primary" onClick={() => setShowAddForm(true)} style={{ marginTop: "1rem" }}>
              ＋ Add Your First Provider
            </Button>
          )}
        </Card>
      )}

      {/* Grouped by Category */}
      {!loading && filtered.length > 0 && (
        <div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
          {Object.entries(PROVIDER_CATEGORIES).map(([categoryName, providerIds]) => {
            const matched = filtered.filter((p) => providerIds.includes(p.provider) || categoryName.includes("API Key"));
            if (categoryName !== "API Key Providers" && matched.length === 0) return null;

            return (
              <div key={categoryName}>
                <h2 style={{ fontSize: "1.2rem", marginBottom: "0.75rem", color: "var(--color-text-muted)" }}>
                  {categoryName}
                </h2>
                <div className="kid-tilt-list" style={{ display: "grid", gap: "1rem", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))" }}>
                  {matched.map((p: ProviderConnection) => {
                    const id = connId(p);
                    const statusVariant = p.testStatus === "active" ? "success" : p.testStatus === "error" ? "danger" : "neutral";
                    const isActive = p.isActive !== false;
                    return (
                      <Card key={id} style={!isActive ? { opacity: 0.55 } : undefined}>
                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: "0.5rem" }}>
                          <div style={{ display: "flex", gap: "0.75rem", alignItems: "center" }}>
                            <ProviderIcon providerId={p.provider} size={36} />
                            <div>
                              <strong style={{ fontSize: "1.25rem", display: "block" }}>{p.name ?? p.provider}</strong>
                              <span style={{ fontFamily: "var(--font-body)", color: "var(--color-text-muted)", fontSize: "0.9rem" }}>
                                {p.provider} · priority {priorityOf(p)}
                              </span>
                            </div>
                          </div>
                          <Badge variant={statusVariant} size="sm" dot>
                            {typeof p.testStatus === "string" ? p.testStatus : "unknown"}
                          </Badge>
                        </div>

                        {p.lastError ? (
                          <div style={{ fontFamily: "var(--font-body)", fontSize: "0.85rem", color: "var(--color-danger)", marginTop: "0.5rem", background: "var(--color-bg-alt)", padding: "0.3rem 0.5rem", border: "1px solid var(--nb-border)" }}>
                            {String(p.lastError)}
                          </div>
                        ) : null}

                        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: "0.85rem", gap: "0.5rem", flexWrap: "wrap" }}>
                          <div style={{ display: "flex", alignItems: "center", gap: "0.4rem" }}>
                            <Button variant="secondary" size="sm" onClick={() => handleMove(p, -1)} title="Raise priority">▲</Button>
                            <Button variant="secondary" size="sm" onClick={() => handleMove(p, 1)} title="Lower priority">▼</Button>
                            <Toggle checked={isActive} onChange={() => handleToggleActive(p)} />
                          </div>
                          <div style={{ display: "flex", gap: "0.4rem" }}>
                            <Button variant="secondary" size="sm" onClick={() => openEdit(p)}>
                              <span className="material-symbols-outlined" style={{ fontSize: 16 }}>edit</span>
                            </Button>
                            <Button
                              variant="accent"
                              size="sm"
                              onClick={() => handleTest(id, p.name ?? p.provider)}
                              disabled={testingId === id}
                            >
                              {testingId === id ? (
                                <span className="material-symbols-outlined animate-spin" style={{ fontSize: 16 }}>progress_activity</span>
                              ) : (
                                <span className="material-symbols-outlined" style={{ fontSize: 16 }}>science</span>
                              )}
                            </Button>
                            <Button
                              variant="danger"
                              size="sm"
                              onClick={() => handleDelete(id, p.name ?? p.provider)}
                            >
                              <span className="material-symbols-outlined" style={{ fontSize: 16 }}>delete</span>
                            </Button>
                          </div>
                        </div>
                      </Card>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Edit Connection Modal */}
      {editing && (
        <div style={{ position: "fixed", inset: 0, backgroundColor: "rgba(0,0,0,0.5)", zIndex: 100, display: "flex", alignItems: "center", justifyContent: "center", padding: "1rem" }}>
          <form onSubmit={handleSaveEdit} className="kid-card kid-wobble" style={{ width: "min(420px, 100%)", background: "var(--color-surface)" }}>
            <h3 style={{ fontSize: "1.4rem", marginTop: 0 }}>✏️ Edit Connection</h3>
            <div style={{ display: "grid", gap: "0.6rem" }}>
              <div>
                <label style={{ fontFamily: "var(--font-body)", fontSize: "0.9rem" }}>Name</label>
                <input className="kid-input" value={editName} onChange={(e) => setEditName(e.target.value)} disabled={savingEdit} autoFocus />
              </div>
              <div>
                <label style={{ fontFamily: "var(--font-body)", fontSize: "0.9rem" }}>Email (optional)</label>
                <input className="kid-input" type="email" value={editEmail} onChange={(e) => setEditEmail(e.target.value)} disabled={savingEdit} />
              </div>
              <div>
                <label style={{ fontFamily: "var(--font-body)", fontSize: "0.9rem" }}>New API Key (leave blank to keep)</label>
                <input className="kid-input" type="password" placeholder="sk-…" value={editApiKey} onChange={(e) => setEditApiKey(e.target.value)} disabled={savingEdit} />
              </div>
            </div>
            <div style={{ display: "flex", gap: "0.5rem", justifyContent: "flex-end", marginTop: "1.25rem" }}>
              <Button variant="secondary" type="button" onClick={() => setEditing(null)} disabled={savingEdit}>
                Cancel
              </Button>
              <Button variant="primary" type="submit" disabled={savingEdit || !editName.trim()}>
                {savingEdit ? "Saving…" : "Save Changes"}
              </Button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
}
